<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>planforge</AssemblyName>
    <RootNamespace>PlanForgeFlow</RootNamespace>
    <ApplicationIcon />
    <PublishAot>false</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PlanForgeFlow.Cli.Tests" />
  </ItemGroup>
</Project>
