using System.Collections.Concurrent;
using System.Text;
using ConcurrencyHunter.Core.Tests.Fixtures;
using ConcurrencyHunter.Providers.LibraryModels;
using ConcurrencyHunter.Providers.LibraryModels.Generation;
using Microsoft.CodeAnalysis;
using Xunit;
using static ConcurrencyHunter.Core.Tests.Fixtures.GenerationRuns;

namespace ConcurrencyHunter.Core.Tests.Generation;

/// <summary>The accessor entry matrix of task 12 (R6, R7): one compiled fixture, one class per accessor-kind/value-kind/act cell, each
/// accessor generated by its <c>M:</c> id and its whole entry compared with an expectation written from the requirements.</summary>
public sealed class AccessorEntryMatrixTests(ClassCache cache) : IClassFixture<ClassCache>
{
    private Matrix Results => cache.Get("results", Run);

    // A cell that comes out wider for a cause this plan does not change is listed here with it.
    private static readonly IReadOnlyDictionary<string, string> Wider = Listed(
        ("vocabulary: the heap does not follow order, so setup's store through Recv._value lands in the probe the setter keeps, and the " +
         "read of the value's object is also a read of a receiver seed", [
            "IndexerSetter/Item/ReadDeep", "Setter/Item/ReadDeep"
        ]));

    /// <summary>The accessor the cell generates.</summary>
    public enum AccessorKind
    {
        Setter,
        StaticSetter,
        IndexerSetter,
        IndexerGetter,
        EventAdd,
        EventRemove,
        StaticEventAdd,
        StaticEventRemove,
        FieldLikeEventAdd,
        FieldLikeEventRemove,
        Getter
    }

    /// <summary>The kind of value the accessor is handed or returns.</summary>
    public enum ValueKind
    {
        Item,
        Action
    }

    /// <summary>What the accessor, or for a field-like event its type's raising member, does.</summary>
    public enum Act
    {
        Store,
        StoreAndFlag,
        FlagOnly,
        ReadDeep,
        HandToExtern,
        Nothing,
        KeepRaised,
        KeepBag,
        KeepRaisedInTaskRun,
        InvokeNow,
        Remove,
        RemoveAndFlag,
        Raised,
        RaisedInTaskRun,
        NeverRaised,
        ReturnField
    }

    /// <summary>One matrix cell.</summary>
    /// <param name="Kind">The accessor the cell generates.</param>
    /// <param name="Value">The kind of value it is handed or returns.</param>
    /// <param name="Act">What it does.</param>
    public sealed record Cell(AccessorKind Kind, ValueKind Value, Act Act)
    {
        public string Name => $"{Kind}/{Value}/{Act}";

        public string Class => $"C_{Kind}_{Value}_{Act}";

        public override string ToString() => Name;
    }

    /// <summary>The generated answers of all cells.</summary>
    /// <param name="Answers">The answer by cell.</param>
    private sealed record Matrix(IReadOnlyDictionary<Cell, GeneratedAnswer> Answers);

    private const string PRELUDE = """
        using System;
        using System.Threading.Tasks;

        namespace Lib
        {
            public static class Sink { public static extern void Take(object value); }
            public class Item { public object Value; }

        """;

    [Fact]
    public void Every_cell_has_no_unsafe_narrowing()
    {
        var failures = Results.Answers.Select(pair => (pair.Key, Comparison: Compare(pair.Key, pair.Value)))
                              .Where(pair => pair.Comparison.IsUnsafeNarrowing)
                              .Select(pair => $"{pair.Key.Name}: {pair.Comparison.Detail}; got {Show(pair.Key, Results.Answers[pair.Key])}")
                              .Order(StringComparer.Ordinal).ToArray();

        Assert.True(failures.Length == 0, $"{failures.Length} unsafe narrowing(s):\n" + string.Join("\n", failures));
    }

    [Fact]
    public void Every_cell_gets_its_expected_answer()
    {
        EvalReport.WriteNames(EvalReport.Folder, "entry-matrix-wider.json", Wider.Keys.Order(StringComparer.Ordinal));
        var failures = new List<string>();
        foreach (var (cell, answer) in Results.Answers.OrderBy(pair => pair.Key.Name, StringComparer.Ordinal))
        {
            var comparison = Compare(cell, answer);
            if (Wider.TryGetValue(cell.Name, out var reason))
            {
                if (comparison.IsExact)
                    failures.Add($"{cell.Name}: listed as wider ({reason}) but got the expected answer");
                else if (comparison.IsUnsafeNarrowing)
                    failures.Add($"{cell.Name}: listed as wider ({reason}) but is unsafe: {comparison.Detail}");
            }
            else if (!comparison.IsExact)
                failures.Add($"{cell.Name}: {comparison.Detail}; got {Show(cell, answer)}");
        }

        foreach (var listed in Wider.Keys.Where(name => Results.Answers.Keys.All(cell => cell.Name != name)))
            failures.Add($"{listed}: listed as wider but is no cell of the matrix");
        Assert.True(failures.Count == 0, $"{failures.Count} cell(s) off the table:\n" + string.Join("\n", failures));
    }

    [Fact]
    public void The_matrix_has_exactly_the_allowed_cells()
    {
        // The allowed combinations, written by hand from the axes and independently of Acts: the setters take both value kinds, the
        // events only Action and the getters only Item; a field-like event's acts are its type's raises.
        const string itemSetter = "Store StoreAndFlag FlagOnly ReadDeep HandToExtern Nothing";
        const string handler = "KeepRaised KeepBag KeepRaisedInTaskRun InvokeNow Remove RemoveAndFlag Nothing";
        const string raises = "Raised RaisedInTaskRun NeverRaised";
        var allowed = new Dictionary<string, string>
        {
            ["Setter/Item"] = itemSetter,
            ["Setter/Action"] = handler,
            ["StaticSetter/Item"] = itemSetter,
            ["StaticSetter/Action"] = handler,
            ["IndexerSetter/Item"] = itemSetter,
            ["IndexerSetter/Action"] = handler,
            ["IndexerGetter/Item"] = "ReadDeep HandToExtern Nothing",
            ["EventAdd/Action"] = handler,
            ["EventRemove/Action"] = handler,
            ["StaticEventAdd/Action"] = handler,
            ["StaticEventRemove/Action"] = handler,
            ["FieldLikeEventAdd/Action"] = raises,
            ["FieldLikeEventRemove/Action"] = raises,
            ["Getter/Item"] = "ReturnField HandToExtern Nothing"
        };
        var expected = allowed.SelectMany(pair => pair.Value.Split(' ').Select(act => $"{pair.Key}/{act}")).Order(StringComparer.Ordinal);

        Assert.Equal(expected, Cells().Select(cell => cell.Name).Order(StringComparer.Ordinal));
        Assert.Equal(expected, Results.Answers.Keys.Select(cell => cell.Name).Order(StringComparer.Ordinal));
    }

    private static EntryComparison Compare(Cell cell, GeneratedAnswer answer) =>
        EntryComparator.Compare(answer, Expected(cell), requireSameModelReason: true);

    /// <summary>The whole expected answer of a cell, from R5, R6 and R7 and TD-034a's rule on library state.</summary>
    /// <param name="cell">The matrix cell.</param>
    private static EntryTruth Expected(Cell cell)
    {
        var expected = new ExpectedModel();
        var reason = cell.Kind switch
        {
            // R7: a field-like event's remove neither runs nor keeps the handler, whatever its type raises.
            AccessorKind.FieldLikeEventRemove => Fate(expected, LibraryFateKind.NotRun),
            // R7: the compiler's add keeps the handler in the event's field; a holder stands only when a trigger runs it in its own
            // execution, so a raise in Task.Run or no raise at all leaves an unknown execution.
            AccessorKind.FieldLikeEventAdd => cell.Act == Act.Raised
                ? Fate(expected, LibraryFateKind.Holder, LibraryHolderKind.This)
                : Fate(expected, LibraryFateKind.UnknownExecution),
            // R6: an indexer getter is generated as a method is; its key is the parameter it reads or hands on.
            AccessorKind.IndexerGetter => cell.Act switch
            {
                Act.ReadDeep => AddEffect(expected, LibraryEffect.DeepReadOf("key")),
                Act.HandToExtern => ModelReasons.UNKNOWN_TOUCH,
                _ => null
            },
            // R5, R6: the field a getter returns is a seed, which has no name in an entry; handing that seed to unseen code is a read
            // of what the receiver holds, which `this` cannot carry (R9's fix of this task).
            AccessorKind.Getter => cell.Act is Act.ReturnField or Act.HandToExtern ? ModelReasons.VOCABULARY : null,
            _ => cell.Value == ValueKind.Item ? ExpectedItemSetter(cell, expected) : ExpectedHandler(cell, expected)
        };
        return reason is null ? EntryTruth.Entry(expected.Build()) : EntryTruth.NoEntry(reason);
    }

    /// <summary>R5, R6 and TD-034a for a setter handed an <c>Item</c>: an instance setter keeps what it stores on <c>this</c> (an
    /// indexer its key too), and a keeper's own fields are part of keeping; a static is state from before the call and no keeper; a
    /// mode field the setter sets without keeping is library state.</summary>
    /// <param name="cell">The setter cell.</param>
    /// <param name="expected">The answer being built.</param>
    private static string? ExpectedItemSetter(Cell cell, ExpectedModel expected)
    {
        if (cell.Act == Act.HandToExtern)
            return ModelReasons.UNKNOWN_TOUCH;
        if (cell.Act == Act.Nothing)
            return null;
        if (cell.Kind == AccessorKind.StaticSetter || cell.Act == Act.FlagOnly)
            return ModelReasons.LIBRARY_STATE;
        if (cell.Act == Act.ReadDeep)
            expected.Effects.Add(LibraryEffect.DeepReadOf("value"));
        expected.Keeps["this"] = (cell.Kind == AccessorKind.IndexerSetter ? ["arg:key", "arg:value"] : new[] { "arg:value" }).Select(Value).ToArray();
        return null;
    }

    /// <summary>R5 and R7 for an accessor handed an <c>Action</c> — a setter or a custom event accessor: a handler a public
    /// <c>Fire</c> runs in its own execution is held by <c>this</c>, which a static member has not; one kept for no member to run,
    /// or run only inside <c>Task.Run</c>, is in an unknown execution; one run in the accessor is <c>invoke-now</c>; one removed or
    /// ignored is <c>not-run</c>. The handler's slot is no library state (task 11), but a mode field set beside a removal is. An
    /// indexer's key is ignored and has no effect.</summary>
    /// <param name="cell">The cell.</param>
    /// <param name="expected">The answer being built.</param>
    private static string? ExpectedHandler(Cell cell, ExpectedModel expected) => cell.Act switch
    {
        Act.KeepRaised => IsStatic(cell.Kind)
            ? Fate(expected, LibraryFateKind.UnknownExecution)
            : Fate(expected, LibraryFateKind.Holder, LibraryHolderKind.This),
        Act.KeepBag or Act.KeepRaisedInTaskRun => Fate(expected, LibraryFateKind.UnknownExecution),
        Act.InvokeNow => Fate(expected, LibraryFateKind.InvokeNow),
        Act.Remove or Act.Nothing => Fate(expected, LibraryFateKind.NotRun),
        Act.RemoveAndFlag => ModelReasons.LIBRARY_STATE,
        _ => throw new InvalidOperationException($"Act {cell.Act} is not a handler act.")
    };

    private static string? Fate(ExpectedModel expected, LibraryFateKind kind, LibraryHolderKind? holder = null)
    {
        expected.Fates.Add(new LibraryFate("value", kind, holder, null));
        return null;
    }

    private static string? AddEffect(ExpectedModel expected, LibraryEffect effect)
    {
        expected.Effects.Add(effect);
        return null;
    }

    private static LibraryValue Value(string text) => LibraryValue.Parse(text)!;

    private static bool IsStatic(AccessorKind kind) => kind is AccessorKind.StaticSetter or AccessorKind.StaticEventAdd or AccessorKind.StaticEventRemove;

    private static IEnumerable<Cell> Cells() =>
        from kind in Enum.GetValues<AccessorKind>()
        from value in Enum.GetValues<ValueKind>()
        from act in Enum.GetValues<Act>()
        let cell = new Cell(kind, value, act)
        where Allowed(cell)
        select cell;

    private static bool Allowed(Cell cell) => Acts(cell.Kind, cell.Value).Contains(cell.Act);

    /// <summary>The acts of an accessor kind under a value kind: none where the kind takes no such value.</summary>
    /// <param name="kind">The accessor kind.</param>
    /// <param name="value">The value kind.</param>
    private static Act[] Acts(AccessorKind kind, ValueKind value) => (kind, value) switch
    {
        (AccessorKind.FieldLikeEventAdd or AccessorKind.FieldLikeEventRemove, ValueKind.Action) => [Act.Raised, Act.RaisedInTaskRun, Act.NeverRaised],
        (AccessorKind.IndexerGetter, ValueKind.Item) => [Act.ReadDeep, Act.HandToExtern, Act.Nothing],
        (AccessorKind.Getter, ValueKind.Item) => [Act.ReturnField, Act.HandToExtern, Act.Nothing],
        (AccessorKind.Setter or AccessorKind.StaticSetter or AccessorKind.IndexerSetter, ValueKind.Item) =>
            [Act.Store, Act.StoreAndFlag, Act.FlagOnly, Act.ReadDeep, Act.HandToExtern, Act.Nothing],
        (AccessorKind.Setter or AccessorKind.StaticSetter or AccessorKind.IndexerSetter or AccessorKind.EventAdd or AccessorKind.EventRemove or
         AccessorKind.StaticEventAdd or AccessorKind.StaticEventRemove, ValueKind.Action) =>
            [Act.KeepRaised, Act.KeepBag, Act.KeepRaisedInTaskRun, Act.InvokeNow, Act.Remove, Act.RemoveAndFlag, Act.Nothing],
        _ => []
    };

    /// <summary>Compiles the fixture once and generates every cell in parallel, as the model generator is used per member.</summary>
    private static Matrix Run()
    {
        var cells = Cells().ToArray();
        var library = Compile(Source(cells));
        Assert.True(library.Compilation is not null, $"{library.Reason}: {string.Join(", ", library.Errors)}");
        Assert.Equal(0, library.ExternBodies);
        var answers = new ConcurrentDictionary<Cell, GeneratedAnswer>();
        Parallel.ForEach(cells, cell =>
        {
            var request = new GenerationRequest(ASSEMBLY, "1.0", AccessorId(library, cell), null, null);
            answers[cell] = ModelGenerator.Trace(request, library, CancellationToken.None).Answer;
        });
        return new Matrix(answers);
    }

    private static string Source(IEnumerable<Cell> cells)
    {
        var source = new StringBuilder(PRELUDE);
        foreach (var cell in cells)
            source.Append(Declaration(cell));
        return source.Append("}\n").ToString();
    }

    /// <summary>One cell's class: the fields its members use, the accessor, and for a handler act other than <c>KeepBag</c> (or a
    /// field-like event that is raised) a public <c>Fire</c>.</summary>
    /// <param name="cell">The cell.</param>
    private static string Declaration(Cell cell)
    {
        var isStatic = IsStatic(cell.Kind);
        var modifier = isStatic ? "static " : "";
        var prefix = isStatic ? "s_" : "_";
        string Field(string name) => prefix + name;

        var members = new List<string>();
        var body = Body(cell, Field);
        var type = cell.Value == ValueKind.Item ? "Item" : "Action";
        members.Add(cell.Kind switch
        {
            AccessorKind.Setter or AccessorKind.StaticSetter => $"public {modifier}{type} P {{ set {{ {body} }} }}",
            AccessorKind.IndexerSetter => $"public {type} this[Item key] {{ set {{ {body} }} }}",
            AccessorKind.IndexerGetter => $"public Item this[Item key] {{ get {{ {body} return null; }} }}",
            AccessorKind.Getter => $"public Item P {{ get {{ {body} }} }}",
            AccessorKind.EventAdd or AccessorKind.StaticEventAdd => $"public {modifier}event Action E {{ add {{ {body} }} remove {{ }} }}",
            AccessorKind.EventRemove or AccessorKind.StaticEventRemove => $"public {modifier}event Action E {{ add {{ }} remove {{ {body} }} }}",
            AccessorKind.FieldLikeEventAdd or AccessorKind.FieldLikeEventRemove => "public event Action E;",
            _ => throw new InvalidOperationException($"Unknown accessor kind {cell.Kind}.")
        });

        var fire = cell.Act switch
        {
            Act.Raised => "E?.Invoke();",
            Act.RaisedInTaskRun => "Task.Run(() => E?.Invoke());",
            Act.KeepRaisedInTaskRun => $"Task.Run(() => {Field("h")}?.Invoke());",
            Act.KeepRaised or Act.InvokeNow or Act.Remove or Act.RemoveAndFlag => $"{Field("h")}?.Invoke();",
            Act.Nothing when cell.Value == ValueKind.Action => $"{Field("h")}?.Invoke();",
            _ => null
        };
        if (fire is not null)
            members.Add($"public {modifier}void Fire() {{ {fire} }}");

        var used = string.Join(' ', members);
        var fields = new (string Type, string Name)[] { ("Action", "h"), ("int", "mode"), ("Item", "key"), ("Item", "value"), ("Item", "f") }
                     .Where(field => used.Contains(Field(field.Name), StringComparison.Ordinal))
                     .Select(field => $"private {modifier}{field.Type} {Field(field.Name)};");

        var source = new StringBuilder().Append("    public ").Append(isStatic ? "static" : "sealed").Append(" class ").Append(cell.Class).Append("\n    {\n");
        foreach (var member in fields.Concat(members))
            source.Append("        ").Append(member).Append('\n');
        return source.Append("    }\n").ToString();
    }

    /// <summary>The accessor's body for a cell; empty for a field-like event, whose accessors the compiler writes.</summary>
    /// <param name="cell">The cell.</param>
    /// <param name="field">The name of a field of the cell's class, static or not.</param>
    private static string Body(Cell cell, Func<string, string> field)
    {
        var store = cell.Kind == AccessorKind.IndexerSetter
            ? $"{field("key")} = key; {field("value")} = value;"
            : $"{field("value")} = value;";
        var flag = $"{field("mode")} = 1;";
        return (cell.Kind, cell.Act) switch
        {
            (AccessorKind.FieldLikeEventAdd or AccessorKind.FieldLikeEventRemove, _) => "",
            (AccessorKind.IndexerGetter, Act.ReadDeep) => "_ = key.ToString();",
            (AccessorKind.IndexerGetter, Act.HandToExtern) => "Sink.Take(key);",
            (AccessorKind.Getter, Act.ReturnField) => $"return {field("f")};",
            (AccessorKind.Getter, Act.HandToExtern) => $"Sink.Take({field("f")}); return null;",
            (AccessorKind.Getter, Act.Nothing) => "return null;",
            (_, Act.Store) => store,
            (_, Act.StoreAndFlag) => $"{store} {flag}",
            (_, Act.FlagOnly) => flag,
            (_, Act.ReadDeep) => $"_ = value.ToString(); {store}",
            (_, Act.HandToExtern) => "Sink.Take(value);",
            (_, Act.KeepRaised or Act.KeepBag or Act.KeepRaisedInTaskRun) => $"{field("h")} = value;",
            (_, Act.InvokeNow) => "value();",
            (_, Act.Remove) => $"{field("h")} -= value;",
            (_, Act.RemoveAndFlag) => $"{field("h")} -= value; {flag}",
            (_, Act.Nothing) => "",
            _ => throw new InvalidOperationException($"Act {cell.Act} has no body for {cell.Kind}.")
        };
    }

    /// <summary>The <c>M:</c> id of the accessor a cell generates.</summary>
    /// <param name="library">The compiled fixture.</param>
    /// <param name="cell">The cell.</param>
    private static string AccessorId(LibraryCompilationResult library, Cell cell)
    {
        var name = cell.Kind switch
        {
            AccessorKind.Setter or AccessorKind.StaticSetter => "set_P",
            AccessorKind.IndexerSetter => "set_Item",
            AccessorKind.IndexerGetter => "get_Item",
            AccessorKind.Getter => "get_P",
            AccessorKind.EventAdd or AccessorKind.StaticEventAdd or AccessorKind.FieldLikeEventAdd => "add_E",
            _ => "remove_E"
        };
        return library.Compilation!.GetTypeByMetadataName($"Lib.{cell.Class}")!.GetMembers(name).OfType<IMethodSymbol>().Single().GetDocumentationCommentId()!;
    }

    private static string Show(Cell cell, GeneratedAnswer answer) => answer.Model is { } model
        ? ModelEntryWriter.Write(model).ToJsonString()
        : answer.ModelReason ?? answer.Reason ?? $"no answer for {cell.Name}";

    private static Dictionary<string, string> Listed(params (string Reason, string[] Cells)[] groups) =>
        groups.SelectMany(group => group.Cells.Select(cell => (cell, group.Reason)))
              .ToDictionary(pair => pair.cell, pair => pair.Reason, StringComparer.Ordinal);

    private sealed class ExpectedModel
    {
        internal List<LibraryEffect> Effects { get; } = [];
        internal List<LibraryFate> Fates { get; } = [];
        internal Dictionary<string, IReadOnlyList<LibraryValue>> Keeps { get; } = new(StringComparer.Ordinal);

        internal LibraryModel Build() => new("M:Lib.Cell.Accessor", [], Effects) { Fates = Fates, Keeps = Keeps };
    }
}
