using ConcurrencyHunter.Providers.LibraryModels;
using ConcurrencyHunter.Providers.LibraryModels.Generation;
using Microsoft.CodeAnalysis;
using Xunit;

namespace ConcurrencyHunter.Core.Tests.Generation;

/// <summary>The accessor evals (R10): the generator on the 12 members of <c>accessors-gold.json</c>, each generated by its <c>M:</c> id
/// from the installed .NET 10 shared framework, its fates against the gold <c>delegateParams</c> and its entry against the gold
/// <c>safeModel</c>. They run only under <c>CH_MODEL_EVALS=1</c>.</summary>
[Collection(ModelEvalTests.COLLECTION)]
public sealed class AccessorEvalTests
{
    [RequiresModelEvalsFact]
    public void No_accessor_answer_is_an_unsafe_narrowing()
    {
        var run = AccessorEvals.InstalledRun;
        var unsafeAnswers = run.Answers.SelectMany(Narrowings).ToArray();

        Assert.Equal(AccessorEvals.MEMBERS, run.Answers.Count);
        Assert.True(unsafeAnswers.Length == 0, $"{unsafeAnswers.Length} unsafe narrowing(s):\n" + string.Join("\n", unsafeAnswers));
    }

    [RequiresModelEvalsFact]
    public void Accessor_answers_pass_the_project_reader()
    {
        foreach (var answer in AccessorEvals.InstalledRun.Answers.Where(answer => answer.Answer.Model is not null))
        {
            var files = ProjectModelFiles.Read("generated.json", ModelEntryWriter.File(answer.Answer.Model!));
            Assert.Empty(files.Rejections);
            var entry = Assert.Single(files.Entries);
            var input = answer.Gold.Input;
            var resolution = ImplementationAssemblies.ForThisProcess().Resolve(input.Assembly, input.Version, input.Package, input.Framework);
            var library = LibraryCompilation.Compile(resolution.Assembly!, CancellationToken.None);
            var compilation = Assert.IsType<Microsoft.CodeAnalysis.CSharp.CSharpCompilation>(library.Compilation);
            var member = Assert.IsAssignableFrom<IMethodSymbol>(DriverSynthesizer.FindMember(compilation, answer.Gold.Member));
            Assert.Null(ProjectModelResolver.EntryRejection(entry, member, compilation));
        }
    }

    [RequiresModelEvalsFact]
    public void Exact_accessor_answers_meet_the_recorded_count()
    {
        var run = AccessorEvals.InstalledRun;
        var lines = AccessorEvals.Lines(run);
        EvalReport.Write(EvalReport.Folder, "accessors", lines);
        var exact = AccessorEvals.Exact(run);
        // Recording sets the count; RecordSnapshot refuses one lower than the snapshot's.
        var recorded = Environment.GetEnvironmentVariable(ModelEvals.RECORD_VARIABLE) == "1" ? exact : ModelEvalTests.RecordedCount("accessorsExact");

        Assert.Equal(AccessorEvals.MEMBERS, lines.Count);
        Assert.True(exact >= recorded,
                    $"{exact} exact accessor answers, under the recorded count {recorded}; inexact:\n" +
                    string.Join("\n", run.Answers.Zip(lines).Where(pair => pair.Second.Verdict != EvalReport.EXACT)
                                         .Select(pair => $"{pair.Second.Id}: {pair.Second.Verdict}; {Show(pair.First)}")));
    }

    [RequiresModelEvalsFact]
    public void No_accessor_member_is_refused_as_an_accessor()
    {
        var answers = AccessorEvals.InstalledRun.Answers;

        Assert.Equal(AccessorEvals.MEMBERS, answers.Count);
        Assert.All(answers, answer =>
        {
            Assert.StartsWith("M:", answer.Gold.Member);
            Assert.True(answer.Answer.Reason is not (GenerationReasons.ACCESSOR or GenerationReasons.MEMBER_NOT_FOUND or GenerationReasons.NO_IMPLEMENTATION),
                        $"{answer.Gold.Member}: {answer.Answer.Reason}: {answer.Answer.Detail}");
        });
    }

    /// <summary>The unsafe narrowings of one answer: each fate the comparator refuses, and the entry when it claims less than the
    /// gold <c>safeModel</c>.</summary>
    /// <param name="answer">The answer.</param>
    private static IEnumerable<string> Narrowings(WholeEntryAnswer answer)
    {
        foreach (var (parameter, gold, answered) in AccessorEvals.Fates(answer))
        {
            if (!ModelEvals.IsSafe(answered, gold))
                yield return $"{answer.Gold.Member}({parameter}): gold {ModelEvals.Show(gold)}, answered {ModelEvals.Show(answered)}";
        }
        var entry = EntryComparator.Compare(answer.Answer, answer.Gold.Truth);
        if (entry.IsUnsafeNarrowing)
            yield return $"{answer.Gold.Member}: {entry.Detail}";
    }

    private static string Show(WholeEntryAnswer answer) =>
        string.Join(", ", AccessorEvals.Fates(answer).Select(fate => $"{fate.Parameter} gold {ModelEvals.Show(fate.Gold)} answered {ModelEvals.Show(fate.Answered)}")
                                     .Append($"entry: {EntryComparator.Compare(answer.Answer, answer.Gold.Truth).Detail}")
                                     .Append($"reason {answer.Answer.Reason ?? "none"}, model reason {answer.Answer.ModelReason ?? "none"}"));
}
